### ISSUE TITLE
Compile toml11 with MinGW cause error in <filesystem>

### ISSUE THREAD

**Issue by chronoxor** [ToruNiina/toml11#135]
Compile in MinGW (mingw-w64/x86_64-8.1.0-release-posix-seh-rt_v6-rev0)
```
#if __cplusplus >= 201703L
#if __has_include(<filesystem>)
#define TOML11_HAS_STD_FILESYSTEM
#include <filesystem>
#endif // has_include(<string_view>)
#endif // cplusplus   >= C++17
```

Cause error:
```
In file included from Z:/soft/Development/MinGW/mingw64/lib/gcc/x86_64-w64-mingw32/8.1.0/include/c++/filesystem:37,
                 from Z:/projects/Projects/PrimeTrader/modules/toml11/toml/parser.hpp:19,
                 from Z:/projects/Projects/PrimeTrader/modules/toml11/toml.hpp:40,
                 from Z:/projects/Projects/PrimeTrader/include/modules/server_module.h:6,
                 from Z:/projects/Projects/PrimeTrader/include/config/config_server_module.h:3,
                 from Z:\projects\Projects\PrimeTrader\source\config\config_server_module.cpp:1:
Z:/soft/Development/MinGW/mingw64/lib/gcc/x86_64-w64-mingw32/8.1.0/include/c++/bits/fs_path.h: In member function 'std::filesystem::__cxx11::path& std::filesystem::__cxx11::path::operator/=(const std::filesystem::__cxx11::path&)':
Z:/soft/Development/MinGW/mingw64/lib/gcc/x86_64-w64-mingw32/8.1.0/include/c++/bits/fs_path.h:237:47: error: no match for 'operator!=' (operand types are 'std::filesystem::__cxx11::path' and 'std::filesystem::__cxx11::path')
    || (__p.has_root_name() && __p.root_name() != root_name()))
                               ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
```

I'll try to provide PR with a fix

**Comment by ToruNiina** [comment]
I have merged it and it seems passing the CI tests. Thank you very much for finding and fixing it!
