### ISSUE TITLE
Compile error on GCC 4.8.5 ( commit: 70d0049)

### ISSUE THREAD

**Issue by WANG-lp** [ToruNiina/toml11#65]
Cannot compile on Centos 7 with GCC 4.8.5:

command: `g++ -std=c++11 toml.cpp`

error info:
```bash

In file included from toml11/toml.hpp:37:0,
                 from toml.cpp:1:
toml11/toml/literal.hpp:14:22: error: missing space between ‘""’ and suffix identifier
 inline ::toml::value operator""_toml(const char* str, std::size_t len)
                      ^
toml.cpp:16:1: error: expected ‘}’ at end of input
 }
 ^
toml.cpp:16:1: error: expected ‘}’ at end of input
toml.cpp:16:1: error: expected ‘}’ at end of input
```

toml.cpp
```cpp
#include "toml11/toml.hpp"
#include <iostream>

int main() {
  const auto data = toml::parse("example.toml");

  // title = "an example toml file"
  std::string title = toml::get<std::string>(data.at("title"));
  std::cout << "the title is " << title << std::endl;

  // nums = [1, 2, 3, 4, 5]
  std::vector<int> nums = toml::get<std::vector<int>>(data.at("nums"));
  std::cout << "the length of `nums` is" << nums.size() << std::endl;

  return 0;
}
```

**Comment by ToruNiina** [comment]
Thank you for reporting!

It is a bug. I have just pushed a patch to `hotfix` branch. After confirming that it passes the auto-tests, I will merge it.
