### ISSUE TITLE
GCC 15.1.1 errors when using C++23

### ISSUE THREAD

**Issue by jvonk** [ToruNiina/toml11#293]
Cannot compile with on Fedora 42 with GCC 15.1.1 using C++23
Seems to be caused by fix 2cbb93d86e7b40d47be78bd24dc034f382f9dc30 for issue #65.

Error info:
```
In file included from build/_deps/toml11-src/include/toml11/impl/literal_impl.hpp:4,
                 from build/_deps/toml11-src/src/literal.cpp:1:
build/_deps/toml11-src/include/toml11/impl/../fwd/literal_fwd.hpp:22:25: error: space between quotes and suffix is deprecated in C++23 [-Werror=deprecated-literal-operator]
   22 | ::toml::value operator"" _toml(const char* str, std::size_t len);
```

**Comment by Chaostheorie** [comment]
This seems like the same error as #285. What revision/version of toml11 are you using?

**Comment by ianabel** [comment]
This is still an issue on main/HEAD. 
The previous patch only fixed one instance in literal_fwd.hpp, g++ finds two other objectionable lines -- fwd/literal_fwd.hpp:29 and impl/literal_impl.hpp:152.

I'll make a PR once I figure out how to run all the checks and tests to confirm that nothing breaks.
